services:

  mongo:
    container_name: mongo-database
    image: mongo:6.0.3
    volumes:
      - ./database:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  aggregator:
    container_name: aggregator-app
    image: node:19.1-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: [ "npm", "run", "start:dev" ]
    depends_on:
      - mongo

  mongo-express:
    container_name: mongo-admin-panel
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
      - aggregator